//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reg2015.RVDataModel
{
    using System;
    
    public enum OfferClassification : short
    {
        Uncnown = 0,
        Operation = 1,
        Monitor = 2,
        PrimaryReception = 3,
        Product = 4,
        PaidReception = 5
    }
}
