//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reg2015.RVDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocumentProduct : tblDocumentCommon
    {
        
    
        partial void OnProductNameChanging(string value);
        partial void OnProductNameChanged();
        private string _ProductName;
        public string ProductName 
        { 
            get { return _ProductName; } 
            set
            {
                if(_ProductName != value)
                {
                    OnProductNameChanging(_ProductName);
                    _ProductName = value;
                    OnProductNameChanged();
                    OnPropertyChanged("ProductName");
                }
            }
        }
        
    
        partial void OnProductModelChanging(string value);
        partial void OnProductModelChanged();
        private string _ProductModel;
        public string ProductModel 
        { 
            get { return _ProductModel; } 
            set
            {
                if(_ProductModel != value)
                {
                    OnProductModelChanging(_ProductModel);
                    _ProductModel = value;
                    OnProductModelChanged();
                    OnPropertyChanged("ProductModel");
                }
            }
        }
    }
}
