//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reg2015.RVDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocumentService : tblDocumentCommon
    {
        
    
        partial void OnServiceDescriptionChanging(string value);
        partial void OnServiceDescriptionChanged();
        private string _ServiceDescription;
        public string ServiceDescription 
        { 
            get { return _ServiceDescription; } 
            set
            {
                if(_ServiceDescription != value)
                {
                    OnServiceDescriptionChanging(_ServiceDescription);
                    _ServiceDescription = value;
                    OnServiceDescriptionChanged();
                    OnPropertyChanged("ServiceDescription");
                }
            }
        }
        
    
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        private string _Name;
        public string Name 
        { 
            get { return _Name; } 
            set
            {
                if(_Name != value)
                {
                    OnNameChanging(_Name);
                    _Name = value;
                    OnNameChanged();
                    OnPropertyChanged("Name");
                }
            }
        }
    }
}
