//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reg2015.RVDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblManipulation : System.ComponentModel.INotifyPropertyChanged
    {
        #region Implement INotifyPropertyChanged
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
        protected virtual void OnPropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        #endregion
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblManipulation()
        {
            this.tblDocumentCommons = new HashSet<tblDocumentCommon>();
            // this.tblDocumentCommons = new System.Collections.ObjectModel.ObservableCollection<tblDocumentCommon>(); // Н.З. тоже работает
        }
    
        
    
        partial void OnIDChanging(System.Guid value);
        partial void OnIDChanged();
        private System.Guid _ID;
        public System.Guid ID 
        { 
            get { return _ID; } 
            set
            {
                if(_ID != value)
                {
                    OnIDChanging(_ID);
                    _ID = value;
                    OnIDChanged();
                    OnPropertyChanged("ID");
                }
            }
        }
        
    
        partial void OnOfferIDChanging(Nullable<System.Guid> value);
        partial void OnOfferIDChanged();
        private Nullable<System.Guid> _OfferID;
        public Nullable<System.Guid> OfferID 
        { 
            get { return _OfferID; } 
            set
            {
                if(_OfferID != value)
                {
                    OnOfferIDChanging(_OfferID);
                    _OfferID = value;
                    OnOfferIDChanged();
                    OnPropertyChanged("OfferID");
                }
            }
        }
        
    
        partial void OnEyeChanging(Eye value);
        partial void OnEyeChanged();
        private Eye _Eye;
        public Eye Eye 
        { 
            get { return _Eye; } 
            set
            {
                if(_Eye != value)
                {
                    OnEyeChanging(_Eye);
                    _Eye = value;
                    OnEyeChanged();
                    OnPropertyChanged("Eye");
                }
            }
        }
        
    
        partial void OnPriceChanging(Nullable<decimal> value);
        partial void OnPriceChanged();
        private Nullable<decimal> _Price;
        public Nullable<decimal> Price 
        { 
            get { return _Price; } 
            set
            {
                if(_Price != value)
                {
                    OnPriceChanging(_Price);
                    _Price = value;
                    OnPriceChanged();
                    OnPropertyChanged("Price");
                }
            }
        }
        
    
        partial void OnDateRealizationChanging(System.DateTime value);
        partial void OnDateRealizationChanged();
        private System.DateTime _DateRealization;
        public System.DateTime DateRealization 
        { 
            get { return _DateRealization; } 
            set
            {
                if(_DateRealization != value)
                {
                    OnDateRealizationChanging(_DateRealization);
                    _DateRealization = value;
                    OnDateRealizationChanged();
                    OnPropertyChanged("DateRealization");
                }
            }
        }
        
    
        partial void OnResponsibleEmpIDChanging(Nullable<System.Guid> value);
        partial void OnResponsibleEmpIDChanged();
        private Nullable<System.Guid> _ResponsibleEmpID;
        public Nullable<System.Guid> ResponsibleEmpID 
        { 
            get { return _ResponsibleEmpID; } 
            set
            {
                if(_ResponsibleEmpID != value)
                {
                    OnResponsibleEmpIDChanging(_ResponsibleEmpID);
                    _ResponsibleEmpID = value;
                    OnResponsibleEmpIDChanged();
                    OnPropertyChanged("ResponsibleEmpID");
                }
            }
        }
        
    
        partial void OnReferralIDChanging(Nullable<System.Guid> value);
        partial void OnReferralIDChanged();
        private Nullable<System.Guid> _ReferralID;
        public Nullable<System.Guid> ReferralID 
        { 
            get { return _ReferralID; } 
            set
            {
                if(_ReferralID != value)
                {
                    OnReferralIDChanging(_ReferralID);
                    _ReferralID = value;
                    OnReferralIDChanged();
                    OnPropertyChanged("ReferralID");
                }
            }
        }
        
    
        partial void OnDateDeleteChanging(Nullable<System.DateTime> value);
        partial void OnDateDeleteChanged();
        private Nullable<System.DateTime> _DateDelete;
        public Nullable<System.DateTime> DateDelete 
        { 
            get { return _DateDelete; } 
            set
            {
                if(_DateDelete != value)
                {
                    OnDateDeleteChanging(_DateDelete);
                    _DateDelete = value;
                    OnDateDeleteChanged();
                    OnPropertyChanged("DateDelete");
                }
            }
        }
        
    
        partial void OnNoteChanging(string value);
        partial void OnNoteChanged();
        private string _Note;
        public string Note 
        { 
            get { return _Note; } 
            set
            {
                if(_Note != value)
                {
                    OnNoteChanging(_Note);
                    _Note = value;
                    OnNoteChanged();
                    OnPropertyChanged("Note");
                }
            }
        }
        
    
        partial void OnDateCreateChanging(System.DateTime value);
        partial void OnDateCreateChanged();
        private System.DateTime _DateCreate;
        public System.DateTime DateCreate 
        { 
            get { return _DateCreate; } 
            set
            {
                if(_DateCreate != value)
                {
                    OnDateCreateChanging(_DateCreate);
                    _DateCreate = value;
                    OnDateCreateChanged();
                    OnPropertyChanged("DateCreate");
                }
            }
        }
        
    
        partial void OnPatientIDChanging(System.Guid value);
        partial void OnPatientIDChanged();
        private System.Guid _PatientID;
        public System.Guid PatientID 
        { 
            get { return _PatientID; } 
            set
            {
                if(_PatientID != value)
                {
                    OnPatientIDChanging(_PatientID);
                    _PatientID = value;
                    OnPatientIDChanged();
                    OnPropertyChanged("PatientID");
                }
            }
        }
        
    
        partial void OnOfferCustomTextChanging(string value);
        partial void OnOfferCustomTextChanged();
        private string _OfferCustomText;
        public string OfferCustomText 
        { 
            get { return _OfferCustomText; } 
            set
            {
                if(_OfferCustomText != value)
                {
                    OnOfferCustomTextChanging(_OfferCustomText);
                    _OfferCustomText = value;
                    OnOfferCustomTextChanged();
                    OnPropertyChanged("OfferCustomText");
                }
            }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<tblDocumentCommon> _tblDocumentCommons;
        public virtual ICollection<tblDocumentCommon> tblDocumentCommons 
        { 
            get { return _tblDocumentCommons; } 
            set
            {
                if(_tblDocumentCommons != value)
                {
                    _tblDocumentCommons = value;
                    OnPropertyChanged("tblDocumentCommons");
                }
            }
        }
    	
        private tblReferral _tblReferral;
        public virtual tblReferral tblReferral 
        { 
            get { return _tblReferral; } 
            set
            {
                if(_tblReferral != value)
                {
                    _tblReferral = value;
                    OnPropertyChanged("tblReferral");
                }
            }
        }
    	
        private tblPatient _tblPatient;
        public virtual tblPatient tblPatient 
        { 
            get { return _tblPatient; } 
            set
            {
                if(_tblPatient != value)
                {
                    _tblPatient = value;
                    OnPropertyChanged("tblPatient");
                }
            }
        }
    	
        private tblEmployee _tblEmployee;
        public virtual tblEmployee tblEmployee 
        { 
            get { return _tblEmployee; } 
            set
            {
                if(_tblEmployee != value)
                {
                    _tblEmployee = value;
                    OnPropertyChanged("tblEmployee");
                }
            }
        }
    	
        private tblOffer _tblOffer;
        public virtual tblOffer tblOffer 
        { 
            get { return _tblOffer; } 
            set
            {
                if(_tblOffer != value)
                {
                    _tblOffer = value;
                    OnPropertyChanged("tblOffer");
                }
            }
        }
    	
    }
}
