//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reg2015.RVDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOffer : System.ComponentModel.INotifyPropertyChanged
    {
        #region Implement INotifyPropertyChanged
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
        protected virtual void OnPropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        #endregion
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOffer()
        {
            this.tblEmployees = new HashSet<tblEmployee>();
            // this.tblEmployees = new System.Collections.ObjectModel.ObservableCollection<tblEmployee>(); // Н.З. тоже работает
            this.tblManipulations = new HashSet<tblManipulation>();
            // this.tblManipulations = new System.Collections.ObjectModel.ObservableCollection<tblManipulation>(); // Н.З. тоже работает
        }
    
        
    
        partial void OnIDChanging(System.Guid value);
        partial void OnIDChanged();
        private System.Guid _ID;
        public System.Guid ID 
        { 
            get { return _ID; } 
            set
            {
                if(_ID != value)
                {
                    OnIDChanging(_ID);
                    _ID = value;
                    OnIDChanged();
                    OnPropertyChanged("ID");
                }
            }
        }
        
    
        partial void OnDocNameChanging(string value);
        partial void OnDocNameChanged();
        private string _DocName;
        public string DocName 
        { 
            get { return _DocName; } 
            set
            {
                if(_DocName != value)
                {
                    OnDocNameChanging(_DocName);
                    _DocName = value;
                    OnDocNameChanged();
                    OnPropertyChanged("DocName");
                }
            }
        }
        
    
        partial void OnProductModelChanging(string value);
        partial void OnProductModelChanged();
        private string _ProductModel;
        public string ProductModel 
        { 
            get { return _ProductModel; } 
            set
            {
                if(_ProductModel != value)
                {
                    OnProductModelChanging(_ProductModel);
                    _ProductModel = value;
                    OnProductModelChanged();
                    OnPropertyChanged("ProductModel");
                }
            }
        }
        
    
        partial void OnShortNameChanging(string value);
        partial void OnShortNameChanged();
        private string _ShortName;
        public string ShortName 
        { 
            get { return _ShortName; } 
            set
            {
                if(_ShortName != value)
                {
                    OnShortNameChanging(_ShortName);
                    _ShortName = value;
                    OnShortNameChanged();
                    OnPropertyChanged("ShortName");
                }
            }
        }
        
    
        partial void OnDefaultPriceChanging(decimal value);
        partial void OnDefaultPriceChanged();
        private decimal _DefaultPrice;
        public decimal DefaultPrice 
        { 
            get { return _DefaultPrice; } 
            set
            {
                if(_DefaultPrice != value)
                {
                    OnDefaultPriceChanging(_DefaultPrice);
                    _DefaultPrice = value;
                    OnDefaultPriceChanged();
                    OnPropertyChanged("DefaultPrice");
                }
            }
        }
        
    
        partial void OnReferreaBonusChanging(decimal value);
        partial void OnReferreaBonusChanged();
        private decimal _ReferreaBonus;
        public decimal ReferreaBonus 
        { 
            get { return _ReferreaBonus; } 
            set
            {
                if(_ReferreaBonus != value)
                {
                    OnReferreaBonusChanging(_ReferreaBonus);
                    _ReferreaBonus = value;
                    OnReferreaBonusChanged();
                    OnPropertyChanged("ReferreaBonus");
                }
            }
        }
        
    
        partial void OnDateDeleteChanging(Nullable<System.DateTime> value);
        partial void OnDateDeleteChanged();
        private Nullable<System.DateTime> _DateDelete;
        public Nullable<System.DateTime> DateDelete 
        { 
            get { return _DateDelete; } 
            set
            {
                if(_DateDelete != value)
                {
                    OnDateDeleteChanging(_DateDelete);
                    _DateDelete = value;
                    OnDateDeleteChanged();
                    OnPropertyChanged("DateDelete");
                }
            }
        }
        
    
        partial void OnClassificationChanging(OfferClassification value);
        partial void OnClassificationChanged();
        private OfferClassification _Classification;
        public OfferClassification Classification 
        { 
            get { return _Classification; } 
            set
            {
                if(_Classification != value)
                {
                    OnClassificationChanging(_Classification);
                    _Classification = value;
                    OnClassificationChanged();
                    OnPropertyChanged("Classification");
                }
            }
        }
        
    
        partial void OnRankChanging(Nullable<int> value);
        partial void OnRankChanged();
        private Nullable<int> _Rank;
        public Nullable<int> Rank 
        { 
            get { return _Rank; } 
            set
            {
                if(_Rank != value)
                {
                    OnRankChanging(_Rank);
                    _Rank = value;
                    OnRankChanged();
                    OnPropertyChanged("Rank");
                }
            }
        }
        
    
        partial void OnSortChanging(int value);
        partial void OnSortChanged();
        private int _Sort;
        public int Sort 
        { 
            get { return _Sort; } 
            set
            {
                if(_Sort != value)
                {
                    OnSortChanging(_Sort);
                    _Sort = value;
                    OnSortChanged();
                    OnPropertyChanged("Sort");
                }
            }
        }
        
    
        partial void OnMonitorTextChanging(string value);
        partial void OnMonitorTextChanged();
        private string _MonitorText;
        public string MonitorText 
        { 
            get { return _MonitorText; } 
            set
            {
                if(_MonitorText != value)
                {
                    OnMonitorTextChanging(_MonitorText);
                    _MonitorText = value;
                    OnMonitorTextChanged();
                    OnPropertyChanged("MonitorText");
                }
            }
        }
        
    
        partial void OnPriceDependenceChanging(string value);
        partial void OnPriceDependenceChanged();
        private string _PriceDependence;
        public string PriceDependence 
        { 
            get { return _PriceDependence; } 
            set
            {
                if(_PriceDependence != value)
                {
                    OnPriceDependenceChanging(_PriceDependence);
                    _PriceDependence = value;
                    OnPriceDependenceChanged();
                    OnPropertyChanged("PriceDependence");
                }
            }
        }
        
    
        partial void OnAnaliseTextChanging(string value);
        partial void OnAnaliseTextChanged();
        private string _AnaliseText;
        public string AnaliseText 
        { 
            get { return _AnaliseText; } 
            set
            {
                if(_AnaliseText != value)
                {
                    OnAnaliseTextChanging(_AnaliseText);
                    _AnaliseText = value;
                    OnAnaliseTextChanged();
                    OnPropertyChanged("AnaliseText");
                }
            }
        }
        
    
        partial void OnDontDriveTextChanging(string value);
        partial void OnDontDriveTextChanged();
        private string _DontDriveText;
        public string DontDriveText 
        { 
            get { return _DontDriveText; } 
            set
            {
                if(_DontDriveText != value)
                {
                    OnDontDriveTextChanging(_DontDriveText);
                    _DontDriveText = value;
                    OnDontDriveTextChanged();
                    OnPropertyChanged("DontDriveText");
                }
            }
        }
        
    
        partial void OnPatientRequiredChanging(string value);
        partial void OnPatientRequiredChanged();
        private string _PatientRequired;
        public string PatientRequired 
        { 
            get { return _PatientRequired; } 
            set
            {
                if(_PatientRequired != value)
                {
                    OnPatientRequiredChanging(_PatientRequired);
                    _PatientRequired = value;
                    OnPatientRequiredChanged();
                    OnPropertyChanged("PatientRequired");
                }
            }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<tblEmployee> _tblEmployees;
        public virtual ICollection<tblEmployee> tblEmployees 
        { 
            get { return _tblEmployees; } 
            set
            {
                if(_tblEmployees != value)
                {
                    _tblEmployees = value;
                    OnPropertyChanged("tblEmployees");
                }
            }
        }
    	
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<tblManipulation> _tblManipulations;
        public virtual ICollection<tblManipulation> tblManipulations 
        { 
            get { return _tblManipulations; } 
            set
            {
                if(_tblManipulations != value)
                {
                    _tblManipulations = value;
                    OnPropertyChanged("tblManipulations");
                }
            }
        }
    	
    }
}
