//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reg2015.RVDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReferral : System.ComponentModel.INotifyPropertyChanged
    {
        #region Implement INotifyPropertyChanged
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
        protected virtual void OnPropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        #endregion
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblReferral()
        {
            this.tblManipulations = new HashSet<tblManipulation>();
            // this.tblManipulations = new System.Collections.ObjectModel.ObservableCollection<tblManipulation>(); // Н.З. тоже работает
        }
    
        
    
        partial void OnIDChanging(System.Guid value);
        partial void OnIDChanged();
        private System.Guid _ID;
        public System.Guid ID 
        { 
            get { return _ID; } 
            set
            {
                if(_ID != value)
                {
                    OnIDChanging(_ID);
                    _ID = value;
                    OnIDChanged();
                    OnPropertyChanged("ID");
                }
            }
        }
        
    
        partial void OnReferralVendorIDChanging(System.Guid value);
        partial void OnReferralVendorIDChanged();
        private System.Guid _ReferralVendorID;
        public System.Guid ReferralVendorID 
        { 
            get { return _ReferralVendorID; } 
            set
            {
                if(_ReferralVendorID != value)
                {
                    OnReferralVendorIDChanging(_ReferralVendorID);
                    _ReferralVendorID = value;
                    OnReferralVendorIDChanged();
                    OnPropertyChanged("ReferralVendorID");
                }
            }
        }
        
    
        partial void OnRegistrationDateChanging(System.DateTime value);
        partial void OnRegistrationDateChanged();
        private System.DateTime _RegistrationDate;
        public System.DateTime RegistrationDate 
        { 
            get { return _RegistrationDate; } 
            set
            {
                if(_RegistrationDate != value)
                {
                    OnRegistrationDateChanging(_RegistrationDate);
                    _RegistrationDate = value;
                    OnRegistrationDateChanged();
                    OnPropertyChanged("RegistrationDate");
                }
            }
        }
        
    
        partial void OnDateCloseChanging(Nullable<System.DateTime> value);
        partial void OnDateCloseChanged();
        private Nullable<System.DateTime> _DateClose;
        public Nullable<System.DateTime> DateClose 
        { 
            get { return _DateClose; } 
            set
            {
                if(_DateClose != value)
                {
                    OnDateCloseChanging(_DateClose);
                    _DateClose = value;
                    OnDateCloseChanged();
                    OnPropertyChanged("DateClose");
                }
            }
        }
        
    
        partial void OnSummCloseChanging(Nullable<decimal> value);
        partial void OnSummCloseChanged();
        private Nullable<decimal> _SummClose;
        public Nullable<decimal> SummClose 
        { 
            get { return _SummClose; } 
            set
            {
                if(_SummClose != value)
                {
                    OnSummCloseChanging(_SummClose);
                    _SummClose = value;
                    OnSummCloseChanged();
                    OnPropertyChanged("SummClose");
                }
            }
        }
        
    
        partial void OnPatientIDChanging(System.Guid value);
        partial void OnPatientIDChanged();
        private System.Guid _PatientID;
        public System.Guid PatientID 
        { 
            get { return _PatientID; } 
            set
            {
                if(_PatientID != value)
                {
                    OnPatientIDChanging(_PatientID);
                    _PatientID = value;
                    OnPatientIDChanged();
                    OnPropertyChanged("PatientID");
                }
            }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<tblManipulation> _tblManipulations;
        public virtual ICollection<tblManipulation> tblManipulations 
        { 
            get { return _tblManipulations; } 
            set
            {
                if(_tblManipulations != value)
                {
                    _tblManipulations = value;
                    OnPropertyChanged("tblManipulations");
                }
            }
        }
    	
        private tblPatient _tblPatient;
        public virtual tblPatient tblPatient 
        { 
            get { return _tblPatient; } 
            set
            {
                if(_tblPatient != value)
                {
                    _tblPatient = value;
                    OnPropertyChanged("tblPatient");
                }
            }
        }
    	
        private tblReferralVendor _tblReferralVendor;
        public virtual tblReferralVendor tblReferralVendor 
        { 
            get { return _tblReferralVendor; } 
            set
            {
                if(_tblReferralVendor != value)
                {
                    _tblReferralVendor = value;
                    OnPropertyChanged("tblReferralVendor");
                }
            }
        }
    	
    }
}
